// Generated by CoffeeScript 1.9.3
(function() {
  var app, bodyParser, express, indexController, server;

  express = require('express');

  bodyParser = require('body-parser');

  indexController = require('./prod/controllers/index.js');

  app = express();

  app.set('view engine', 'jade');

  app.set('views', __dirname + '/prod/views');

  app.use(express["static"](__dirname + '/prod/public'));

  app.get('/', indexController.index);

  app.get('/templates/:templateDir/:templateName', indexController.templates);

  server = app.listen(4270, function() {
    return console.log("Express server listening on port " + (server.address().port));
  });

}).call(this);
